name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]
        numpy-version: ["1.20.3", "1.21.0"]

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install NumPy ${{ matrix.numpy-version }}
        run: python -m pip install numpy==${{ matrix.numpy-version }}

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Build and test
        run: python setup.py build_ext --inplace && python -m pytest
